<?php
// Config
require_once 'config.php';

// Common includes
require_once $settings['path']['base'] . '/lib/vmConnect.class.php';
require_once $settings['path']['base'] . '/lib/asyncVmTasks.class.php';

// VM connection object
$vm = new vmConnect($settings);

// Get all known system ips
$vm->exec('hostname -I');
$system['iplist'] = explode(' ', $vm->getResult());

// Get first IPv6 address from system
foreach ($system['iplist'] as $ip) {
	if(strpos($ip, ':') !== false) {
		$system['ipv6'] = $ip;
		break;
	}
}
if (!isset($system['ipv6'])) {
	echo 'This system has no IPv6 address setup. Please fix your network interface first';
	exit;
}

############ CP PLUGIN #############
require_once $settings['path']['plugin_dir'] . "/cp/{$settings['plugin']['cpplugin']}.plugin.php";

/*
A variable should be generated by the control panel as a list of domains that are present in the control panel.
This should also inlude all aliases and addon domains, but you can probably leave out subdomains.
Please use the following (very uncomplicated) format:
$domains = Array
(
    [0] => domain.nl
    [1] => domain.com
    [2] => subdomain.domain.eu
)
*/

############ DNS PLUGIN ############
require_once $settings['path']['plugin_dir'] . "/dns/{$settings['plugin']['dnsplugin']}.plugin.php";


// Logging
$log[] = "\n-----------------\n\n";
$log[] = var_export($vm->getResult(true), true);
$log[] = var_export($vm->getError(true), true);
$log[] = var_export($vm->getLog(true), true);

if (is_object($dnsObj)) {
	$log[] = var_export($dnsObj->getResult(true), true);
	$log[] = var_export($dnsObj->getError(true), true);
	$log[] = var_export($dnsObj->getRequest(true), true);
	$log[] = var_export($dnsObj->getResponse(true), true);	
}

file_put_contents($settings['path']['log_dir'] . '/' . $settings['vm']['host'] . '.log', implode("\n-----------------\n\n", $log), FILE_APPEND);

header('Location: index.php?status=done');
